/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ProjectsNewIndexRouteImport } from './routes/projects/new/index'
import { Route as ProjectsComponentsProjectsListRouteImport } from './routes/projects/components/projects-list'
import { Route as ProjectsComponentsProjectsHeaderRouteImport } from './routes/projects/components/projects-header'
import { Route as ProjectsComponentsProjectsContentRouteImport } from './routes/projects/components/projects-content'
import { Route as ProjectsComponentsEmptyProjectsRouteImport } from './routes/projects/components/empty-projects'
import { Route as ProjectsComponentsCreateProjectDialogRouteImport } from './routes/projects/components/create-project-dialog'
import { Route as ProjectsNewComponentsCreateProjectFormRouteImport } from './routes/projects/new/components/create-project-form'
import { Route as DashboardComponentsContentCostBreakdownRouteImport } from './routes/dashboard/components/content/cost-breakdown'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewIndexRoute = ProjectsNewIndexRouteImport.update({
  id: '/projects/new/',
  path: '/projects/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsComponentsProjectsListRoute =
  ProjectsComponentsProjectsListRouteImport.update({
    id: '/projects/components/projects-list',
    path: '/projects/components/projects-list',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsComponentsProjectsHeaderRoute =
  ProjectsComponentsProjectsHeaderRouteImport.update({
    id: '/projects/components/projects-header',
    path: '/projects/components/projects-header',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsComponentsProjectsContentRoute =
  ProjectsComponentsProjectsContentRouteImport.update({
    id: '/projects/components/projects-content',
    path: '/projects/components/projects-content',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsComponentsEmptyProjectsRoute =
  ProjectsComponentsEmptyProjectsRouteImport.update({
    id: '/projects/components/empty-projects',
    path: '/projects/components/empty-projects',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsComponentsCreateProjectDialogRoute =
  ProjectsComponentsCreateProjectDialogRouteImport.update({
    id: '/projects/components/create-project-dialog',
    path: '/projects/components/create-project-dialog',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsNewComponentsCreateProjectFormRoute =
  ProjectsNewComponentsCreateProjectFormRouteImport.update({
    id: '/projects/new/components/create-project-form',
    path: '/projects/new/components/create-project-form',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardComponentsContentCostBreakdownRoute =
  DashboardComponentsContentCostBreakdownRouteImport.update({
    id: '/dashboard/components/content/cost-breakdown',
    path: '/dashboard/components/content/cost-breakdown',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/projects/components/create-project-dialog': typeof ProjectsComponentsCreateProjectDialogRoute
  '/projects/components/empty-projects': typeof ProjectsComponentsEmptyProjectsRoute
  '/projects/components/projects-content': typeof ProjectsComponentsProjectsContentRoute
  '/projects/components/projects-header': typeof ProjectsComponentsProjectsHeaderRoute
  '/projects/components/projects-list': typeof ProjectsComponentsProjectsListRoute
  '/projects/new/': typeof ProjectsNewIndexRoute
  '/dashboard/components/content/cost-breakdown': typeof DashboardComponentsContentCostBreakdownRoute
  '/projects/new/components/create-project-form': typeof ProjectsNewComponentsCreateProjectFormRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/projects/components/create-project-dialog': typeof ProjectsComponentsCreateProjectDialogRoute
  '/projects/components/empty-projects': typeof ProjectsComponentsEmptyProjectsRoute
  '/projects/components/projects-content': typeof ProjectsComponentsProjectsContentRoute
  '/projects/components/projects-header': typeof ProjectsComponentsProjectsHeaderRoute
  '/projects/components/projects-list': typeof ProjectsComponentsProjectsListRoute
  '/projects/new': typeof ProjectsNewIndexRoute
  '/dashboard/components/content/cost-breakdown': typeof DashboardComponentsContentCostBreakdownRoute
  '/projects/new/components/create-project-form': typeof ProjectsNewComponentsCreateProjectFormRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/projects/components/create-project-dialog': typeof ProjectsComponentsCreateProjectDialogRoute
  '/projects/components/empty-projects': typeof ProjectsComponentsEmptyProjectsRoute
  '/projects/components/projects-content': typeof ProjectsComponentsProjectsContentRoute
  '/projects/components/projects-header': typeof ProjectsComponentsProjectsHeaderRoute
  '/projects/components/projects-list': typeof ProjectsComponentsProjectsListRoute
  '/projects/new/': typeof ProjectsNewIndexRoute
  '/dashboard/components/content/cost-breakdown': typeof DashboardComponentsContentCostBreakdownRoute
  '/projects/new/components/create-project-form': typeof ProjectsNewComponentsCreateProjectFormRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard/'
    | '/projects/'
    | '/settings/'
    | '/projects/components/create-project-dialog'
    | '/projects/components/empty-projects'
    | '/projects/components/projects-content'
    | '/projects/components/projects-header'
    | '/projects/components/projects-list'
    | '/projects/new/'
    | '/dashboard/components/content/cost-breakdown'
    | '/projects/new/components/create-project-form'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/projects'
    | '/settings'
    | '/projects/components/create-project-dialog'
    | '/projects/components/empty-projects'
    | '/projects/components/projects-content'
    | '/projects/components/projects-header'
    | '/projects/components/projects-list'
    | '/projects/new'
    | '/dashboard/components/content/cost-breakdown'
    | '/projects/new/components/create-project-form'
  id:
    | '__root__'
    | '/'
    | '/dashboard/'
    | '/projects/'
    | '/settings/'
    | '/projects/components/create-project-dialog'
    | '/projects/components/empty-projects'
    | '/projects/components/projects-content'
    | '/projects/components/projects-header'
    | '/projects/components/projects-list'
    | '/projects/new/'
    | '/dashboard/components/content/cost-breakdown'
    | '/projects/new/components/create-project-form'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  ProjectsComponentsCreateProjectDialogRoute: typeof ProjectsComponentsCreateProjectDialogRoute
  ProjectsComponentsEmptyProjectsRoute: typeof ProjectsComponentsEmptyProjectsRoute
  ProjectsComponentsProjectsContentRoute: typeof ProjectsComponentsProjectsContentRoute
  ProjectsComponentsProjectsHeaderRoute: typeof ProjectsComponentsProjectsHeaderRoute
  ProjectsComponentsProjectsListRoute: typeof ProjectsComponentsProjectsListRoute
  ProjectsNewIndexRoute: typeof ProjectsNewIndexRoute
  DashboardComponentsContentCostBreakdownRoute: typeof DashboardComponentsContentCostBreakdownRoute
  ProjectsNewComponentsCreateProjectFormRoute: typeof ProjectsNewComponentsCreateProjectFormRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new/': {
      id: '/projects/new/'
      path: '/projects/new'
      fullPath: '/projects/new/'
      preLoaderRoute: typeof ProjectsNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/components/projects-list': {
      id: '/projects/components/projects-list'
      path: '/projects/components/projects-list'
      fullPath: '/projects/components/projects-list'
      preLoaderRoute: typeof ProjectsComponentsProjectsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/components/projects-header': {
      id: '/projects/components/projects-header'
      path: '/projects/components/projects-header'
      fullPath: '/projects/components/projects-header'
      preLoaderRoute: typeof ProjectsComponentsProjectsHeaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/components/projects-content': {
      id: '/projects/components/projects-content'
      path: '/projects/components/projects-content'
      fullPath: '/projects/components/projects-content'
      preLoaderRoute: typeof ProjectsComponentsProjectsContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/components/empty-projects': {
      id: '/projects/components/empty-projects'
      path: '/projects/components/empty-projects'
      fullPath: '/projects/components/empty-projects'
      preLoaderRoute: typeof ProjectsComponentsEmptyProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/components/create-project-dialog': {
      id: '/projects/components/create-project-dialog'
      path: '/projects/components/create-project-dialog'
      fullPath: '/projects/components/create-project-dialog'
      preLoaderRoute: typeof ProjectsComponentsCreateProjectDialogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new/components/create-project-form': {
      id: '/projects/new/components/create-project-form'
      path: '/projects/new/components/create-project-form'
      fullPath: '/projects/new/components/create-project-form'
      preLoaderRoute: typeof ProjectsNewComponentsCreateProjectFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/components/content/cost-breakdown': {
      id: '/dashboard/components/content/cost-breakdown'
      path: '/dashboard/components/content/cost-breakdown'
      fullPath: '/dashboard/components/content/cost-breakdown'
      preLoaderRoute: typeof DashboardComponentsContentCostBreakdownRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  ProjectsComponentsCreateProjectDialogRoute:
    ProjectsComponentsCreateProjectDialogRoute,
  ProjectsComponentsEmptyProjectsRoute: ProjectsComponentsEmptyProjectsRoute,
  ProjectsComponentsProjectsContentRoute:
    ProjectsComponentsProjectsContentRoute,
  ProjectsComponentsProjectsHeaderRoute: ProjectsComponentsProjectsHeaderRoute,
  ProjectsComponentsProjectsListRoute: ProjectsComponentsProjectsListRoute,
  ProjectsNewIndexRoute: ProjectsNewIndexRoute,
  DashboardComponentsContentCostBreakdownRoute:
    DashboardComponentsContentCostBreakdownRoute,
  ProjectsNewComponentsCreateProjectFormRoute:
    ProjectsNewComponentsCreateProjectFormRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
