// ─── Seed Data ───────────────────────────────────────────────────────────────
// Demo data used to populate the app before a real API is connected.

import { Project, Deployment } from './types';

export const SEED_PROJECTS: Project[] = [
  {
    id: 'acme-website',
    name: 'Acme Website',
    description: 'Main marketing and landing page for Acme Corp',
    type: 'website',
    status: 'running',
    region: 'us-east-1',
    url: 'https://acme.meshscale.io',
    uptime: '99.98%',
    lastDeployed: '2 hours ago',
    lastDeployedBy: 'Eddie Lake',
    cpu: 12,
    memory: 34,
    instances: 3,
  },
  {
    id: 'survival-craft',
    name: 'SurvivalCraft Server',
    description: 'Minecraft-like survival game server with 50 player capacity',
    type: 'game-server',
    status: 'running',
    region: 'eu-west-1',
    uptime: '99.81%',
    lastDeployed: '5 days ago',
    lastDeployedBy: 'Eddie Lake',
    cpu: 67,
    memory: 72,
    instances: 1,
  },
  {
    id: 'payments-api',
    name: 'Payments API',
    description: 'REST API handling payment processing and billing',
    type: 'api',
    status: 'running',
    region: 'us-west-2',
    url: 'https://api.payments.meshscale.io',
    uptime: '100%',
    lastDeployed: '3 days ago',
    lastDeployedBy: 'Jamik Tashpulatov',
    cpu: 23,
    memory: 41,
    instances: 5,
  },
  {
    id: 'email-worker',
    name: 'Email Worker',
    description: 'Background worker for transactional email queue processing',
    type: 'worker',
    status: 'stopped',
    region: 'us-east-1',
    uptime: '87.3%',
    lastDeployed: '1 week ago',
    lastDeployedBy: 'Eddie Lake',
    cpu: 0,
    memory: 0,
    instances: 0,
  },
  {
    id: 'battle-arena',
    name: 'Battle Arena',
    description: 'Competitive 5v5 multiplayer arena game server',
    type: 'game-server',
    status: 'deploying',
    region: 'ap-southeast-1',
    uptime: '95.2%',
    lastDeployed: 'Just now',
    lastDeployedBy: 'Eddie Lake',
    cpu: 0,
    memory: 0,
    instances: 0,
  },
  {
    id: 'analytics-sync',
    name: 'Analytics Sync',
    description: 'Hourly cron job to sync analytics events to data warehouse',
    type: 'cron',
    status: 'running',
    region: 'us-east-1',
    uptime: '99.4%',
    lastDeployed: '2 weeks ago',
    lastDeployedBy: 'Jamik Tashpulatov',
    cpu: 3,
    memory: 8,
    instances: 1,
  },
];

export const SEED_DEPLOYMENTS: Deployment[] = [
  {
    id: 'dep-1',
    projectId: 'acme-website',
    commit: 'a1b2c3d',
    branch: 'main',
    message: 'Update hero section copy',
    status: 'success',
    createdAt: '2 hours ago',
    duration: '1m 23s',
    deployedBy: 'Eddie Lake',
  },
  {
    id: 'dep-2',
    projectId: 'acme-website',
    commit: 'e4f5g6h',
    branch: 'main',
    message: 'Fix mobile nav overflow',
    status: 'success',
    createdAt: '1 day ago',
    duration: '1m 45s',
    deployedBy: 'Eddie Lake',
  },
  {
    id: 'dep-3',
    projectId: 'acme-website',
    commit: 'i7j8k9l',
    branch: 'feature/new-cta',
    message: 'Add new CTA button to pricing',
    status: 'failed',
    createdAt: '2 days ago',
    duration: '0m 42s',
    deployedBy: 'Eddie Lake',
  },
  {
    id: 'dep-4',
    projectId: 'payments-api',
    commit: 'm1n2o3p',
    branch: 'main',
    message: 'Add Stripe webhook handler',
    status: 'success',
    createdAt: '3 days ago',
    duration: '2m 10s',
    deployedBy: 'Jamik Tashpulatov',
  },
  {
    id: 'dep-5',
    projectId: 'payments-api',
    commit: 'q4r5s6t',
    branch: 'main',
    message: 'Fix race condition in checkout',
    status: 'success',
    createdAt: '5 days ago',
    duration: '1m 55s',
    deployedBy: 'Jamik Tashpulatov',
  },
  {
    id: 'dep-6',
    projectId: 'survival-craft',
    commit: 'u7v8w9x',
    branch: 'main',
    message: 'Update world generation seed',
    status: 'success',
    createdAt: '5 days ago',
    duration: '3m 20s',
    deployedBy: 'Eddie Lake',
  },
  {
    id: 'dep-7',
    projectId: 'email-worker',
    commit: 'y1z2a3b',
    branch: 'main',
    message: 'Add retry logic for failed sends',
    status: 'failed',
    createdAt: '1 week ago',
    duration: '0m 55s',
    deployedBy: 'Eddie Lake',
  },
  {
    id: 'dep-8',
    projectId: 'battle-arena',
    commit: 'c4d5e6f',
    branch: 'main',
    message: 'Initial deployment',
    status: 'in-progress',
    createdAt: 'Just now',
    duration: '-',
    deployedBy: 'Eddie Lake',
  },
  {
    id: 'dep-9',
    projectId: 'analytics-sync',
    commit: 'g7h8i9j',
    branch: 'main',
    message: 'Add BigQuery export support',
    status: 'success',
    createdAt: '2 weeks ago',
    duration: '1m 05s',
    deployedBy: 'Jamik Tashpulatov',
  },
  {
    id: 'dep-10',
    projectId: 'payments-api',
    commit: 'k1l2m3n',
    branch: 'hotfix/refund',
    message: 'Hotfix: refund flow null check',
    status: 'success',
    createdAt: '1 week ago',
    duration: '1m 30s',
    deployedBy: 'Jamik Tashpulatov',
  },
];
